'use client'
import "./globals.css";
import Navbar from "./components/NavBar";
import AuthInitializer from "./components/AuthInitializer";
import { Toaster } from "react-hot-toast";
import Script from "next/script";



// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   icons: {
//     icon: '/favicon.ico', // ניתן להשתמש גם ב-png או svg
//   },
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body
       
      >
        <AuthInitializer/>
        <Toaster/>
       <Navbar/>
        {children}
        <Script
        strategy="afterInteractive"
        src="https://cdn.enable.co.il/licenses/enable-L353865821g3r7h0-1224-66930/init.js"
        onLoad={() => {
          console.log('ENABLE script loaded');
        }}
      />
      </body>
    </html>
  );
}
